import "./globals.css";
import type { Metadata } from "next";
import { Cairo } from 'next/font/google'


export const metadata: Metadata = {
  title: "Mohamed Ahmed - Portfolio",
  description: "Generated by create next app",
};

const cairo = Cairo({ subsets: ["latin"] })

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cairo.className}>{children}</body>
    </html>
  );
}
